# Introduction
Data used in this project is published by the United States Census Bureau, detailing the population's education attainment across different race, gender, and age groups. We aim to use the education attainment data from 2012 to 2021 with a focus on the black population to delve into trends in education, dissecting the evolution of African American education during the last decade. 

Education is fundamentally significant for a person's development in the society. An overview of educational status of a particular subset of the society thus offers lenses through which we can understand broader socio-economic dynamics and challenges. By analyzing the education attainment data, we can identify patterns and disparities in educational access and achievements in specific demographic groups. This understanding can inform policy decisions, educational reforms, and targeted initiatives aimed at reducing educational inequalities and fostering a more inclusive and equitable society. Additionally, this analysis can highlight the progress or lack thereof in educational attainment, serving as a critical indicator of the nation's development and its ability to adapt to the demands of black people as a minority group.

Some interesting questions we seek to answer through our data visualizations:

1. How has the percentage of black male and female individuals with a Bachelor's degree or higher changed from the decade of discussion? (Trend in Higher Education) How has the percentage of black male and female individuals with no education changed over the decade? (Trend in No Education History)

2. What's the trend for black males and females to have received a Doctoral degree over the decade for different age groups? (Doctoral Degree across Different Age Groups)

3. How do black males and females differ in percentages in education attainments? Can we find patterns from a year to year comparison? (Year to Year Education Attainment Comparison)

4. Overall, how would one best describe the different paths in education development between black males and females over the ten year window? (Overall Education Development)

5. During the time of COVID, were there drastic/noticeable patterns in education attainments? (COVID Impact on Education Attainment)

6. What do our plots implicate for the socio-economic dynamics of the black population of the United States? Or what potential policy direction is hinted at if there is any?


